[package]
name = "wisp-core"
description = "Sessions, pager, and query runner for Wisp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
wisp-drivers = { path = "../drivers", version = "0.1.0" }
wisp-store = { path = "../store", version = "0.1.0" }
