[package]
name = "wisp"
description = "Wisp database client application"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "wisp"
path = "src/main.rs"

[features]
bench-stress = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
wisp-store = { path = "../store", version = "0.1.0", default-features = false }
wisp-ui = { path = "../ui", version = "0.1.0", default-features = false }
